language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - ~/.platformio
install:
- pip install platformio
- pio update
script:
- platformio run -e nodemcu
notifications:
  email:
    on_success: albert.suwandhi@gmail.com
    on_failure: albert.suwandhi@gmail.com
env:
  global:
    secure: cJqfQUqNWdPVuFCRPykN+XvWco/082mNhiWCmYUghlJmHJsAaFzrrZu4Se2kcOn7BMzleuYHkwMq/NNrqqlPllaRHItiPSxPAUFwRY6IiwkGjJ3BzzUSkTn5WHXFlp0d/NC3K5HtWlZK4YYCzy+hflYTD/asAe/sae/ZIxOCrJCoPhiD1jeA3/ECyhSGHVowAWi02ydtDt/o4QwI6aS3ThQPrQOXbkz66F2JEMFu2/epZb5227DIORovgNU4J9dU9/+AhB/RtTat9BSGaN057B7QA6SfR5ZfuNLvcVBuzXUlW1Oz2Biob9cwL2gt5MqkHyNse8w7FZbvZPYFJlRyW3ImzMn5+nQWMu2xYtzRpOKnJuzvaIadWWRKt4QzYEco9XB6VrNDjbEgR4UODK3mMb5ApKiK2pkuYqIVVeSssKQZ09LBQbni4v304Nj4G4PDMNGA6ReUje0etxiXlMNyymXmRR2s3E4O+qYoBUGU1UV7E9rFxDp6+7969ZM6ZyevuWwnxsJIyslzZTJulTfHyNwUghjnFc2+BUhm/KKxsG9ze4hTnPR4EhGfH/vm/wRGT+Sy4rFvvEQA9m2TjC/RwfVLDIh80wupikfAu9qGUSqdrZhcD6QQwhJpd62hepvZNSS4zR3ejDGF6sBjhd1pE5t4aFlrrzzouShGFkobsao=
deploy:
  provider: releases
  api_key:
    secure: EE6pemKMpetuKRWde44/OKtmrIGMKfDn5vfGt14ulT/CShN800qKVkS7KskFwUt5t3k4Mqq05N9WDt5KB12SMeQATiObO54YVfyNxQXTjuHU8M9KDcygHk7E+/53V7yY7rAGy2EEjJy5TABBzYou2A93k24RuC/JahatHm1rgi5CASecy7OW3snuwlp1tdvhIxJc9aTJaCidgkK3dNfd5+MiuJl56agIRNOl0t0ZQow1olgzYIKsqSBBHBUKUiXYSeAKu9KcFI/AX6vqzJeYjL//PNwDr+n72Uh+o07mz+sGrmicFk5nv/i+QgEC8QFmQAV6uaEyIDzIMPJBnUI3WZoSMN9eg0T1qk5+MAcpyuyTg3c6cXtMbuH1H+iFGaSjJ8JTOr0kJQQ5Id8W1qNaZLHbj+pDOGurZPVKFymIbAPO5Z+Wnrt3IyVBWPb7rJyB4AzWtFWO83G2OjkyveN5ixr3ENHpuz3LcxwFYXxf0xM/KjDPBExseGgfVI1Sf0uCFwWQciGSHQ3C0x4b8qp4NfsfCmGUYp3tqbPFY1Luy99xL2PhNGvQ4LMTgnVr4VWRGBIMgq+NP6bNx1cO9hKtiqJjEukq3ElBDrXPfl6YwD+UYfHKWiM9OSR4nZJPkaDEm5yLSyEKq9V3YdBxa1Ty2dbigYVMa7Ll6Q47dGlZCjI=
  file: $TRAVIS_BUILD_DIR/.pioenvs/nodemcu/firmware.elf
  on:
    repo: albertsuwandhi/PlatformIO-Travis
